jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Cleanup Function
        uses: fjogeleit/http-request-action@v1.4.0
        with:
          url: "https://mfooewemvofleynanjkb.supabase.co/functions/v1/cleanup-expired-courses"
          method: GET
          # 🚨 CHANGE 1: REMOVE bearerToken
          # REMOVED: bearerToken: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

          # 🚨 CHANGE 2: ADD headers WITH EXPLICIT AUTHORIZATION
          headers: '{"Authorization": "Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"}'
