name: Scheduled Cleanup of Expired Courses

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour, adjust as needed
  workflow_dispatch:      # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Cleanup Function with Auth
        uses: fjogeleit/http-request-action@v1.4.0
        with:
          url: "https://mfooewemvofleynanjkb.supabase.co/functions/v1/cleanup-expired-courses"
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
